---
- name: Install MongoDB 3.2
  hosts: all
  become: true
  roles:
    - db


#  tasks:
  # Добавим ключ репозитория для последующей работы с ним
#  - name: Add APT key
#    apt_key:
#      url: https://www.mongodb.org/static/pgp/server-3.2.asc
#      state: present

  # Подключаем репозиторий с пакетами mongodb
#  - name: Add APT repository
#    apt_repository:
#      repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
#      state: present

  # Выполним установку пакета
#  - name: Install mongodb package
#    apt:
#      name: mongodb-org
#      state: present
#      allow_unauthenticated: yes

  # Включаем сервис
#  - name: Configure service supervisor
#    systemd:
#      name: mongod
#      enabled: yes
